name: Предложение
description: Идея по улучшению Сундука
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Задача
      description: Какую проблему это решает? Что неудобно сейчас?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Предлагаемое решение
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Альтернативы
      description: Что ещё рассматривали (в том числе сторонние инструменты).
    validations:
      required: false
